### ISSUE TITLE
Restore backup

### ISSUE THREAD

**Issue by babgond** [YunoHost-Apps/snipeit_ynh#13]
Hello,
I want to restore a backup file in Snipe-IT on YunoHost.
The command "php artisan db:restore yourdumpfilename.sql" does not seem to work.
Do you have another solution?
Thank you

**Comment by babgond** [comment]
I tried the following command
`/usr/bin/php /var/www/snipeit/artisan db:restore yourdumpfilename.sql`

I have the following message that appears
> Command "db:restore" is not defined.
> 
>   Did you mean one of these?
>       db:seed
>       queue:restart
>       snipeit:restore-users

**Comment by kay0u** [comment]
Hi, you should take a look [here](https://github.com/snipe/snipe-it/issues/2785#issuecomment-254972810) :-)

**Comment by kay0u** [comment]
Otherwise, you can't just use the YunoHost backup/restore system?

**Comment by babgond** [comment]
hello, the backup comes from a snipe it independent of YunoHost.
while waiting for a more pleasant version, I restored the .sql file with phpMyAdmin.
