### ISSUE TITLE
.env APP_URL incorrect

### ISSUE THREAD

**Issue by oXyiGYJ** [YunoHost-Apps/snipeit_ynh#38]
### Describe the bug

I believe in the most recent update something changed the `APP_URL` setting in `.env` to start with http instead of https. When this happens, you are unable to assign assets to anything, as it cannot find the assets or users when checking it out. Once I changed http to https and cleared cache, it worked fine.

### Context

- Hardware: VPS
- YunoHost version: 11.2.5
- I have access to my server: SSH, Webmin, Web admin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: not initially
  - If yes, please explain: only changed the .env to fix the issue based on Snipe-ITs recommendation
- Using, or trying to install package version/branch: 6.2.3~ynh1
- If upgrading, current package version: This started after the upgrade to 6.2.3~ynh1

### Steps to reproduce

- Upgrade from 6.2.2 (or a fresh install? Unsure on the fresh install)
- Go to assign an asset
- Choose the entity to assign it to (either User, Asset, or Location) and search in the field for that entity
- Error it gives is "The results could not be loaded"

### Expected behavior

Show a list of assets, locations or users and allow you to search/select them.

### Logs

Nothing showed up in the logs for this specific issue, but had been reported to Snipe-IT before.

I am unsure if this is unique to me, or not, but I do know I did not edit the `.env` file before this, so the https would not have been changed by me directly.

**Comment by Salamandar** [comment]
Fixed
